# ETF Sector and Country Exposure

This notebook calculates sector and country concentration risk using the percentage allocation of each ETF. Exposure data will be stored in long format so each ETF can have multiple sector and country rows.

In [1]:
import pandas as pd

sector_template = pd.DataFrame(
    columns=["Ticker", "Sector", "Weight_Percent"]
)

country_template = pd.DataFrame(
    columns=["Ticker", "Country", "Weight_Percent"]
)

sector_template.to_csv(
    "../data/raw/etf_sector_exposure.csv",
    index=False
)

country_template.to_csv(
    "../data/raw/etf_country_exposure.csv",
    index=False
)

print("Sector and country exposure templates created.")

Sector and country exposure templates created.

In [2]:
etf_universe = pd.read_csv(
    "../data/processed/etf_universe_clean.csv"
)

print("Asset classes:")
print(etf_universe["Asset_Class"].value_counts())

print("\nETF list:")
display(
    etf_universe[
        [
            "ETF_ID",
            "Ticker",
            "ETF_Name",
            "Asset_Class",
            "Sector_Focus"
        ]
    ]
)

Asset classes:
Asset_Class
Equity      12
Bond         6
Gold         1
Property     1
Name: count, dtype: int64

ETF list:

,ETF_ID,Ticker,ETF_Name,Asset_Class,Sector_Focus
0,VWRP,VWRP.L,Vanguard FTSE All-World UCITS ETF,Equity,Broad
1,SWDA,SWDA.L,iShares Core MSCI World UCITS ETF,Equity,Broad
2,VUAG,VUAG.L,Vanguard S&P 500 UCITS ETF,Equity,Broad large-cap
3,ISF,ISF.L,iShares Core FTSE 100 UCITS ETF,Equity,Broad large-cap
4,EQQQ,EQQQ.L,Invesco EQQQ Nasdaq-100 UCITS ETF,Equity,Growth / Nasdaq
5,VEUR,VEUR.L,Vanguard FTSE Developed Europe UCITS ETF,Equity,Broad
6,VJPN,VJPN.L,Vanguard FTSE Japan UCITS ETF,Equity,Broad
7,VFEG,VFEG.L,Vanguard FTSE Emerging Markets UCITS ETF,Equity,Broad
8,ICHN,ICHN.AS,iShares MSCI China UCITS ETF,Equity,Regional
9,IUIT,IUIT.L,iShares S&P 500 Information Technology Sector ...,Equity,Technology
10,IUHC,IUHC.L,iShares S&P 500 Health Care Sector UCITS ETF,Equity,Healthcare
11,INRG,INRG.L,iShares Global Clean Energy Transition UCITS ETF,Equity,Clean energy
12,VGOV,VGOV.L,Vanguard U.K. Gilt UCITS ETF,Bond,Government bonds
13,IGLO,IGLO.L,iShares Global Govt Bond UCITS ETF,Bond,Government bonds
14,IBTG,IBTG.L,iShares $ Treasury Bond 1-3yr UCITS ETF GBP He...,Bond,Short-term government bonds
15,AGGG,AGGG.L,iShares Core Global Aggregate Bond UCITS ETF,Bond,Aggregate bonds
16,CORP,CORP.L,iShares Global Corp Bond UCITS ETF,Bond,Investment-grade corporate bonds
17,GHYS,GHYS.L,iShares Global High Yield Corp Bond GBP Hedged...,Bond,High-yield corporate bonds
18,SGLN,SGLN.L,iShares Physical Gold ETC,Gold,Gold
19,IWDP,IWDP.L,iShares Developed Markets Property Yield UCITS...,Property,Property / REITs

In [3]:
exposure_requirements = etf_universe[
    [
        "ETF_ID",
        "Ticker",
        "ETF_Name",
        "Asset_Class"
    ]
].copy()

exposure_requirements["Needs_Sector_Data"] = (
    exposure_requirements["Asset_Class"]
    .astype(str)
    .str.contains("Equity", case=False, na=False)
)

exposure_requirements["Needs_Country_Data"] = (
    ~exposure_requirements["Asset_Class"]
    .astype(str)
    .str.contains(
        "Alternative|Commodity|Gold",
        case=False,
        na=False
    )
)

display(exposure_requirements)

print(
    "ETFs requiring sector data:",
    exposure_requirements["Needs_Sector_Data"].sum()
)

print(
    "ETFs requiring country data:",
    exposure_requirements["Needs_Country_Data"].sum()
)

,ETF_ID,Ticker,ETF_Name,Asset_Class,Needs_Sector_Data,Needs_Country_Data
0,VWRP,VWRP.L,Vanguard FTSE All-World UCITS ETF,Equity,True,True
1,SWDA,SWDA.L,iShares Core MSCI World UCITS ETF,Equity,True,True
2,VUAG,VUAG.L,Vanguard S&P 500 UCITS ETF,Equity,True,True
3,ISF,ISF.L,iShares Core FTSE 100 UCITS ETF,Equity,True,True
4,EQQQ,EQQQ.L,Invesco EQQQ Nasdaq-100 UCITS ETF,Equity,True,True
5,VEUR,VEUR.L,Vanguard FTSE Developed Europe UCITS ETF,Equity,True,True
6,VJPN,VJPN.L,Vanguard FTSE Japan UCITS ETF,Equity,True,True
7,VFEG,VFEG.L,Vanguard FTSE Emerging Markets UCITS ETF,Equity,True,True
8,ICHN,ICHN.AS,iShares MSCI China UCITS ETF,Equity,True,True
9,IUIT,IUIT.L,iShares S&P 500 Information Technology Sector ...,Equity,True,True
10,IUHC,IUHC.L,iShares S&P 500 Health Care Sector UCITS ETF,Equity,True,True
11,INRG,INRG.L,iShares Global Clean Energy Transition UCITS ETF,Equity,True,True
12,VGOV,VGOV.L,Vanguard U.K. Gilt UCITS ETF,Bond,False,True
13,IGLO,IGLO.L,iShares Global Govt Bond UCITS ETF,Bond,False,True
14,IBTG,IBTG.L,iShares $ Treasury Bond 1-3yr UCITS ETF GBP He...,Bond,False,True
15,AGGG,AGGG.L,iShares Core Global Aggregate Bond UCITS ETF,Bond,False,True
16,CORP,CORP.L,iShares Global Corp Bond UCITS ETF,Bond,False,True
17,GHYS,GHYS.L,iShares Global High Yield Corp Bond GBP Hedged...,Bond,False,True
18,SGLN,SGLN.L,iShares Physical Gold ETC,Gold,False,False
19,IWDP,IWDP.L,iShares Developed Markets Property Yield UCITS...,Property,False,True

ETFs requiring sector data: 12
ETFs requiring country data: 19

In [4]:
print("No sector data required:")
display(
    exposure_requirements.loc[
        ~exposure_requirements["Needs_Sector_Data"],
        ["Ticker", "ETF_Name", "Asset_Class"]
    ]
)

print("\nNo country data required:")
display(
    exposure_requirements.loc[
        ~exposure_requirements["Needs_Country_Data"],
        ["Ticker", "ETF_Name", "Asset_Class"]
    ]
)

No sector data required:

    Ticker                                           ETF_Name Asset_Class
12  VGOV.L                       Vanguard U.K. Gilt UCITS ETF        Bond
13  IGLO.L                 iShares Global Govt Bond UCITS ETF        Bond
14  IBTG.L  iShares $ Treasury Bond 1-3yr UCITS ETF GBP He...        Bond
15  AGGG.L       iShares Core Global Aggregate Bond UCITS ETF        Bond
16  CORP.L                 iShares Global Corp Bond UCITS ETF        Bond
17  GHYS.L  iShares Global High Yield Corp Bond GBP Hedged...        Bond
18  SGLN.L                          iShares Physical Gold ETC        Gold
19  IWDP.L  iShares Developed Markets Property Yield UCITS...    Property

No country data required:

    Ticker                   ETF_Name Asset_Class
18  SGLN.L  iShares Physical Gold ETC        Gold

In [5]:
exposure_requirements.loc[
    ~exposure_requirements["Needs_Country_Data"],
    ["Ticker", "ETF_Name", "Asset_Class"]
]

    Ticker                   ETF_Name Asset_Class
18  SGLN.L  iShares Physical Gold ETC        Gold